### ISSUE TITLE
Use polyfil on extension api calls

### ISSUE THREAD

**Issue by TheEZIC** [Cavitedev/osu-subdivide-nations#100]
I recommend you to use this library to prevent undefined behaviour of some extension api methods in different browsers
https://github.com/mozilla/webextension-polyfill?ysclid=lonhzzb6qa286801949

**Comment by Cavitedev** [comment]
I'm already using it. Even though I've added it as a depndency and let vite dynamically import the code

**Comment by Cavitedev** [comment]
As explained I don't see the issue with the current code
