### ISSUE TITLE
Add empty space (or flag placeholder) when page is loading.

### ISSUE THREAD

**Issue by TheEZIC** [Cavitedev/osu-subdivide-nations#28]
You need to inject CSS to website page and add extra space or flag placeholder to page content.
![image](https://github.com/Cavitedev/osu-subdivide-nations/assets/35061249/1ecdc5b5-bb3d-4c5f-8160-99c752162655)
It's very annoying when my content in this row is blinking.

**Comment by Cavitedev** [comment]
Do you mean forcing space to be added even before it gets updated?

**Comment by Cavitedev** [comment]
I cannot think of any CSS rule that properly adds that space without adding space no language flags and other stuff

**Comment by TheEZIC** [comment]
> I cannot think of any CSS rule that properly adds that space without adding space no language flags and other stuff

You can subscribe on table element update. And on insert node event in mutations add empty space node. And then you'll can fill them all with flags.

**Comment by Cavitedev** [comment]
Done with version 2.7.0
