### ISSUE TITLE
Add webpack/vite support instead of sh script

### ISSUE THREAD

**Issue by TheEZIC** [Cavitedev/osu-subdivide-nations#29]
It will be more convenient to work with familiar front-end tools for contributors. And also helps to separate code to different files. If you want it I can share my webpack config for chrome extension.

**Comment by Cavitedev** [comment]
Sounds interesting. I didn't do enough research about those tools

**Comment by Cavitedev** [comment]
In the end I'm doing things in the old crude way. Whatever is used from now should compile to Chrome and Firefox picking the right manifests

**Comment by Cavitedev** [comment]
I don't feel fully persuaded about this. I cannot see a decent way to set this up for both Chrome and Firefox v3. Even though the only difference is the manifest file

**Comment by Cavitedev** [comment]
I'll still give it a try

**Comment by TheEZIC** [comment]
You can use file loader depends on your CLI argument flag when you try to build your application

**Comment by Cavitedev** [comment]
After trying many tools. I believe I have some foundation now. Where I can build or watch the code on the platforms I desire by running node scripts

**Comment by Cavitedev** [comment]
This should be closed. I'd keep splitting the files. but now it's coded in typescript and compiled through node
