### ISSUE TITLE
Add region rank to osu profile

### ISSUE THREAD

**Issue by TheEZIC** [Cavitedev/osu-subdivide-nations#40]
![image](https://github.com/Cavitedev/osu-subdivide-nations/assets/35061249/6bb66db6-1307-4320-a784-5a14df8ea8e4)

**Comment by Cavitedev** [comment]
What API should I use for that? I need to discuss that with W A H

**Comment by Cavitedev** [comment]
![image](https://github.com/Cavitedev/osu-subdivide-nations/assets/52750778/6e1d194b-3462-4fce-999c-c0ac2019c3bb)
Coming soon

**Comment by Cavitedev** [comment]
Now it's uploaded. Enjoy this new feature
