### ISSUE TITLE
Extension not trusted by Enhanced Safe Browsing

### ISSUE THREAD

**Issue by h3oCharles** [Cavitedev/osu-subdivide-nations#78]
![image](https://github.com/Cavitedev/osu-subdivide-nations/assets/8020330/6d01d972-d8ab-4539-863b-2465b7be4536)

probably should be marked as invalid, but i may as well report that i have encountered this

**Comment by Cavitedev** [comment]
Oh. Thank you I'll take a look into it

**Comment by Cavitedev** [comment]
This just means I could keep improving the store site and extension to get featured. Downloads and rating with 5 stars would help speed up the process

![image](https://github.com/Cavitedev/osu-subdivide-nations/assets/52750778/c161040c-2c29-4538-b85c-7dd066ae3c86)

**Comment by Cavitedev** [comment]
It got featured so I've fixed it niceeeeeeee!
